"""Add title field to songs table

Revision ID: 149f346acf01
Revises: a574a93f1bf5
Create Date: 2025-08-24 21:47:47.777294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149f346acf01'
down_revision = 'a574a93f1bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('title', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'title')
    # ### end Alembic commands ###
